# Generated by Django 3.2.9 on 2021-12-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('genero', models.CharField(max_length=40)),
                ('canTemportadas', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
