# Generated by Django 3.2.9 on 2021-12-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_auto_20211214_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('año', models.IntegerField(null=True)),
                ('genero', models.CharField(max_length=40)),
                ('cantemporadas', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('edad', models.IntegerField(null=True)),
                ('direccion', models.CharField(max_length=40)),
                ('fechaNacimiento', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='usuarioNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='persona',
        ),
        migrations.DeleteModel(
            name='series',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='año',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='director',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='duracion',
            field=models.IntegerField(null=True),
        ),
    ]
