# Generated by Django 3.2.9 on 2021-12-16 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_auto_20211215_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fechaNacimiento',
            field=models.IntegerField(null=True),
        ),
    ]
