# Generated by Django 3.2.9 on 2021-12-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_auto_20211216_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fechaNacimiento',
            field=models.DateField(),
        ),
    ]
