# Generated by Django 3.2.9 on 2021-12-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_alter_usuario_fechanacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='mensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.CharField(max_length=360)),
            ],
        ),
        migrations.DeleteModel(
            name='serie',
        ),
        migrations.AlterField(
            model_name='usuarionewsletter',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
