# Generated by Django 3.2.9 on 2021-12-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0009_auto_20211219_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='edad',
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(default='hello', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='email', max_length=254),
        ),
    ]
