# Generated by Django 3.2.9 on 2021-12-20 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0010_auto_20211219_2301'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuarioNewsletter',
            new_name='newsletter',
        ),
    ]
