# Generated by Django 3.2.9 on 2021-12-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0011_rename_usuarionewsletter_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mensajeContacto',
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.TimeField(null=True),
        ),
    ]
