# Generated by Django 3.2.9 on 2022-01-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0012_auto_20211222_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
    ]
